name: Update commit hash
on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00

jobs:
  change-commit:
    name: Change the commit hash to the latest upstream one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change commit
        run: |
          commit_and_tag=$(git ls-remote https://github.com/mborgerson/xemu 'refs/tags/build-*' | awk -F/ 'END { print $0 }')
          commit=${commit_and_tag%%	*}
          tag=${commit_and_tag##*/}
          sed -i "/xemu.git/{n;s/tag.*/tag: $tag/;n;s/commit.*/commit: $commit/}" app.xemu.xemu.yml
          date=${tag#build-}
          year_month_day=$(date -I -d ${date%????})
          sed -i "s|    <release .*|    <release date=\"$year_month_day\" version=\"$tag\" />|" app.xemu.xemu.metainfo.xml
      - name: Push the change
        run: |
          git config user.name CI
          git config user.email ""
          git add app.xemu.xemu.yml app.xemu.xemu.metainfo.xml
          git commit -m "Update xemu.git" || exit 0
          git push
