name: Update commit hash
on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00

jobs:
  change-commit:
    name: Change the commit hash to the latest upstream one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change commit
        run: |
          commit_and_tag=$(git ls-remote --sort=-version:refname https://github.com/mborgerson/xemu 'refs/tags/gh-release/*' | head -1)
          commit=${commit_and_tag%%	*}
          version=${commit_and_tag##*/}
          sed -i "/xemu.git/{n;s/commit.*/commit: $commit/}" app.xemu.xemu.yml
          # if the commit has changed then modify the appstream file too
          git diff --quiet || sed -i "s|    <release .*|    <release date=\"$(date -I)\" version=\"$version\" />|" app.xemu.xemu.metainfo.xml
      - name: Push the change
        run: |
          git config user.name CI
          git config user.email ""
          git commit -am "Update xemu.git" || exit 0
          git push
